package com.example.novel;

import java.util.ArrayList;

public class Data_novel {
    public static String[][] data = new String[][]{
            {"Bumi", "Tere Liye", "27 Januari 2014", "440 Halaman", "Namaku Raib, usiaku 15 tahun, kelas sepuluh. Aku anak perempuan seperti kalian, adik-adik kalian, tetangga kalian. Aku punya dua kucing, namanya si Putih dan si Hitam. Mama dan papaku menyenangkan. Guru-guru di sekolahku seru. Teman-temanku baik dan kompak. Aku sama seperti remaja kebanyakan, kecuali satu hal. Sesuatu yang kusimpan sendiri sejak kecil. Sesuatu yang menakjubkan. Namaku, Raib. Dan aku bisa menghilang.", "https://scoopadm.apps-foundry.com/ebook-covers/46405/image_highres/ID_EIB2019MTH03EIB.jpg"},
            {"Bulan", "Tere Liye", "12 Maret 2015", "400 Halaman", "Namanya Seli, usianya 15 tahun, kelas sepuluh. Dia sama seperti remaja yang lain. Menyukai hal yang sama, mendengarkan lagu-lagu yang sama, pergi ke gerai fast food, menonton serial drama, film, dan hal-hal yang disukai remaja. Tetapi ada sebuah rahasia kecil Seli yang tidak pernah diketahui siapa pun. Sesuatu yang dia simpan sendiri sejak kecil. Sesuatu yang menakjubkan dengan tangannya. Namanya Seli. Dan tangannya bisa mengeluarkan petir. ", "https://cdn.idntimes.com/content-images/community/2019/03/images-6e813839724446556057c6dcca5a0a66.jpeg"},
            {"Matahari", "Tere Liye", "25 Juli 2016", "440 Halaman", "Namanya Ali, 15 tahun, kelas X. Jika saja orangtuanya mengizinkan, seharusnya dia sudah duduk di tingkat akhir ilmu fisika program doktor di universitas ternama. Ali tidak menyukai sekolahnya, guru-gurunya, teman-teman sekelasnya. Semua membosankan baginya. Tapi sejak dia mengetahui ada yang aneh pada diriku dan Seli, teman sekelasnya, hidupnya yang membosankan berubah seru. Aku bisa menghilang, dan Seli bisa mengeluarkan petir. Ali sendiri punya rahasia kecil. Dia bisa berubah menjadi beruang raksasa. Kami bertiga kemudian bertualang ke tempat-tempat menakjubkan. Namanya Ali. Dia tahu sejak dulu dunia ini tidak sesederhana yang dilihat orang. Dan di atas segalanya, dia akhirnya tahu persahabatan adalah hal yang paling utama.", "https://cdn.idntimes.com/content-images/community/2019/03/jual-buku-matahari-novel-tere-liye-terbaru-harga-murah-790x790-0188c5e76a65597f1e8f7c877ceefa76.jpg"},
            {"Bintang", "Tere Liye", "12 Juni 2017", "440 Halaman", "Kami bertiga teman baik. Remaja, murid kelas sebelas. Penampilan kami sama seperti murid SMA lainnya. Tapi kami menyimpan rahasia besar. Namaku Raib, aku bisa menghilang. Seli, teman semejaku, bisa mengeluarkan petir dari telapak tangannya. Dan Ali, si biang kerok sekaligus si genius, bisa berubah menjadi beruang raksasa. Kami bertiga kemudian bertualang ke dunia paralel yang tidak diketahui banyak orang, yang disebut Klan Bumi, Klan Bulan, Klan Matahari, dan Klan Bintang. Kami bertemu tokoh-tokoh hebat. Penduduk klan lain. Ini petualangan keempat kami. Setelah tiga kali berhasil menyelamatkan dunia paralel dari kehancuran besar, kami harus menyaksikan bahwa kamilah yang melepaskan “musuh besar”-nya. Ini ternyata bukan akhir petualangan, ini justru awal dari semuanya… .", "https://cdn.idntimes.com/content-images/community/2019/03/jual-bintang-novel-tere-liye-terbaru-buku-ke-empat-dari-serial-bumi-harga-murah-caeb9b125a01783030a3b28b78ae891c.jpg"},
            {"Ceros Dan Batozar", "Tere Liye", "28 May 2018", "440 Halaman", "Awalnya kami hanya mengikuti karyawisata biasa seperti murid-murid sekolah lain. Hingga Ali, dengan kegeniusan dan keisengannya, memutuskan menyelidiki sebuah ruangan kuno. Kami tiba di bagian dunia paralel lainnya, menemui petarung kuat, mendapat kekuatan baru serta teknik-teknik menakjubkan. Dunia paralel ternyata sangat luas, dengan begitu banyak orang hebat di dalamnya. Kisah ini tentang petualangan tiga sahabat. Raib bisa menghilang. Seli bisa mengeluarkan petir. Dan Ali bisa melakukan apa saja.", "https://cdn.idntimes.com/content-images/community/2019/03/jual-ceros-dan-batozar-novel-tere-liye-terbaru-buku-ke-empat-koma-lima-dari-serial-bumi-harga-murah-fa1ee6182ccdce17533274fc76252633.jpg"},
            {"Komet", "Tere Liye", " 28 May 201", "440 Halaman", "Setelah “musuh besar” kami lolos, dunia paralel dalam situasi genting. Hanya soal waktu, pertempuran besar akan terjadi. Bagaimana jika ribuan petarung yang bisa menghilang, mengeluarkan petir, termasuk teknologi maju lainnya muncul di permukaan Bumi? Tidak ada yang bisa membayangkan kekacauan yang akan terjadi. Situasi menjadi lebih rumit lagi saat Ali, pada detik terakhir, melompat ke portal menuju Klan Komet. Kami bertiga tersesat di klan asing untuk mencari pusaka paling hebat di dunia paralel. Buku ini berkisah tentang petualangan tiga sahabat. Raib bisa menghilang. Seli bisa mengeluarkan petir. Dan Ali bisa melakukan apa saja. Buku ini juga berkisah tentang persahabatan yang mengharukan, pengorbanan yang tulus, keberanian, dan selalu berbuat baik. Karena sejatinya, itulah kekuatan terbesar di dunia paralel.", "https://cdn.idntimes.com/content-images/community/2019/03/40093223-uy2362-ss2362-99deac417d18131f26ad35afdd625f82.jpg"},
            {"Komet Minor", "Tere Liye", "Maret 2019", "440 Halaman", "Pertarungan melawan Si Tanpa Mahkota akan berakhir di sini. Siapapun yang menang, semua berakhir di sini, di klan Komet Minor, tempat aliansi Para Pemburu pernah dibentuk, dan pusaka hebat pernah diciptakan. Dalam saga terakhir melawan Si Tanpa Mahkota, aku, Seli dan Ali menemukan teman seperjalanan yang hebat, yang bersama-sama melewati berbagai rintangan. Memahami banyak hal, berlatih teknik baru, dan bertarung bersama-sama. Inilah kisah kami. Tentang persahabatan sejati. Tentang pengorbanan. Tentang ambisi. Tentang memaafkan. ", "https://cdn.idntimes.com/content-images/community/2019/03/id-km2019mth03km-a4e2193cfca66eac73bea088f6885a31.jpg"},

    };

    public static ArrayList<Novel> getListData(){
        ArrayList<Novel> list = new ArrayList<>();
        for (String[] aData : data){
            Novel novel = new Novel();
            novel.setJudul(aData[0]);
            novel.setPenulis(aData[1]);
            novel.setTanggal(aData[2]);
            novel.setHal(aData[3]);
            novel.setSinopsis(aData[4]);
            novel.setPhoto(aData[5]);
            list.add(novel);
        }
        return list;
    }
}
